### ISSUE TITLE
Single Album flip

### ISSUE THREAD

**Issue by wcampbell91** [wcampbell91/capstone-recordz#20]
# User Story
* When I click on the view more info button on a single album card, I should see it flip to the backside that displays more information about the selected album...

# Dev Notes
* To flip card for more info
```html
<div class="flip-box">
  <div class="flip-box-inner">
    <div class="flip-box-front">
      <h2>Album Art</h2>
    </div>
    <div class="flip-box-back">
      <h2>Detailed Album info</h2>
    </div>
  </div>
</div>
```
```css
.flip-box {
  background-color: transparent;
  width: 300px;
  height: 200px;
  border: 1px solid #f1f1f1;
  perspective: 1000px;
}

.flip-box-inner {
  position: relative;
  width: 100%;
  height: 100%;
  text-align: center;
  transition: transform 0.8s;
  transform-style: preserve-3d;
}

.flip-box:hover .flip-box-inner {
  transform: rotateY(180deg);
}

.flip-box-front, .flip-box-back {
  position: absolute;
  width: 100%;
  height: 100%;
  backface-visibility: hidden;
}

.flip-box-front {
  background-color: #bbb;
  color: black;
}

.flip-box-back {
  background-color: dodgerblue;
  color: white;
  transform: rotateY(180deg);
}
```
* to do this on click of the "view more info" button I think you can just have it perform the transform that flips the card...
