### ISSUE TITLE
Single Record View Page

### ISSUE THREAD

**Issue by wcampbell91** [wcampbell91/capstone-recordz#6]
# User Story
* As a user, when I click the view button on one of my album cards, I should be redirected to a single Record view page. This page should display the album artwork the focal point of the page.  ( #19 )

* When I hover on the album cover, I should see a bar appear over the bottom of the image with a message that displays the artist name and album name, as well as a button to view more info. ( #19 )

* When I click the more info button, I should see the album flip over and display more detailed information about the selected album such as tracklist, year, genre and a button that links to the discogs page for the album. ( #20 )

# Dev Notes
* on hover bar appears
```html
<div class="infoBar">
    <div class="artist">
      <h2 class="text-left">Artist:</h2>
      <h4 class="text-left">${artist}</h4>
      <button class="btn btn-primary">See More Info></button>
    </div>
    <div class="album">
      <h2 class="text-right">Album:</h2>
      <h4 class="text-right">${album}</h4>
    </div>
</div>
```
```css
.infoBar {
  display: grid;
  grid-template: 1 / 2;
  background-color: #f4511e;
  border: none;
  color: white;
  opacity: 0;
  transition: 0.3s;
}

.artist {
  grid-column: 1 / 1;
  text-align: left
}

.album {
  grid-column: 2 / 2;
  text-align: right;
}

.myDiv:hover {opacity: .6}
```

* To flip card for more info ( #20 )

<img width="941" alt="Screen Shot 2020-09-06 at 8 08 36 PM" src="https://user-images.githubusercontent.com/62917622/92544973-ca912900-f214-11ea-899f-9b43ae3a141d.png">

<img width="750" alt="Screen Shot 2020-09-06 at 8 08 06 PM" src="https://user-images.githubusercontent.com/62917622/92544982-d41a9100-f214-11ea-82c9-fa9edf59156b.png">
